/** @type {import('tailwindcss').Config} */
export default {
  content: ["./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-tertiary-container": "#ffe6be",
        "surface-tint": "#685d4c",
        "tertiary-fixed": "#ffdea5",
        tertiary: "#684c0b",
        "surface-variant": "#ece2ca",
        "primary-fixed": "#f0e0cb",
        "surface-container": "#f7edd5",
        "on-surface": "#201b0d",
        primary: "#594f3f",
        "primary-fixed-dim": "#d3c5b0",
        "surface-dim": "#e3d9c2",
        "secondary-fixed": "#e7e6ac",
        "on-secondary": "#ffffff",
        "surface-bright": "#fff8ef",
        "on-primary-container": "#f6e7d1",
        "surface-container-high": "#f1e7cf",
        "surface-container-lowest": "#ffffff",
        "tertiary-container": "#836423",
        "inverse-surface": "#353020",
        "on-primary": "#ffffff",
        error: "#ba1a1a",
        "on-tertiary": "#ffffff",
        "outline-variant": "#c9c7b8",
        "primary-container": "#726755",
        "surface-container-low": "#fdf3db",
        secondary: "#616133",
        "on-secondary-container": "#676738",
        "tertiary-fixed-dim": "#e9c176",
        surface: "#fff8ef",
        "inverse-primary": "#d3c5b0",
        "secondary-fixed-dim": "#cac992",
        "on-tertiary-fixed": "#261900",
        "on-primary-fixed-variant": "#4f4535",
        "surface-container-highest": "#ece2ca",
        "secondary-container": "#e7e6ac",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
        "on-background": "#201b0d",
        "on-primary-fixed": "#221a0d",
        "inverse-on-surface": "#faf0d8",
        "on-surface-variant": "#48473c",
        background: "#fff8ef",
        outline: "#79776b",
        "error-container": "#ffdad6",
        "on-tertiary-fixed-variant": "#5d4201",
        "on-secondary-fixed": "#1d1d00",
        "on-secondary-fixed-variant": "#49491e",
        "brand-dark": "#2C2416",
        "brand-cream": "#F2E8D0",
      },
      fontFamily: {
        headline: ["Newsreader", "serif"],
        body: ["Manrope", "sans-serif"],
        label: ["Manrope", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
    },
  },
  plugins: [require("@tailwindcss/forms"), require("@tailwindcss/container-queries")],
};
